### ISSUE TITLE
 Failed at the node-dht-sensor@0.4.3 postinstall script.

### ISSUE THREAD

**Issue by AetherCabuto** [momenso/node-dht-sensor#117]
Hi, i've been all day trying to install the dht module into my computer but I keep getting this error and it's driving me crazy, I'm a bit new into programming and nodejs.
![image](https://user-images.githubusercontent.com/77704925/105111063-f18a2200-5a74-11eb-93ee-e1329aae0eaf.png)

Does anyone know how to fix it?
Thanks in advance!

**Comment by momenso** [comment]
You're supposed to install it on your raspberry pi running Raspbian or similar.
