### ISSUE TITLE
correct output format

### ISSUE THREAD

**Issue by Sarfarazsajjad** [momenso/node-dht-sensor#19]
I am using DHT11 and trying to run your second code example, currently I am getting this output

Outdoor: 896.0C, 896.0%

please explain how to understand or convert these values into simple understandable values

![screen shot 2015-05-12 at 9 35 03 pm](https://cloud.githubusercontent.com/assets/4182883/7592781/d80d3d6e-f8ee-11e4-931e-e4cbc6f3f57e.png)

**Comment by momenso** [comment]
Looks very similar to Issue #18.
