### ISSUE TITLE
getting an error when installing the library

### ISSUE THREAD

**Issue by AlexSnoeren** [momenso/node-dht-sensor#20]
hi All,

I am getting following error when trying to install the library on pi:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'node-dht-sensor' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 silly cache add args [ 'node-dht-sensor', null ]
6 verbose cache add spec node-dht-sensor
7 silly cache add parsed spec { raw: 'node-dht-sensor',
7 silly cache add   scope: null,
7 silly cache add   name: 'node-dht-sensor',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed node-dht-sensor@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'node-dht-sensor', range: '*', hasData: false }
12 silly mapToRegistry name node-dht-sensor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/node-dht-sensor
16 verbose addNameRange registry:https://registry.npmjs.org/node-dht-sensor not in flight; fetching
17 verbose request uri https://registry.npmjs.org/node-dht-sensor
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:19:49
20 verbose request id 1f20a176687171af
21 verbose etag "B7YPB0FKNLKETDYQX2WQ50DG0"
22 http request GET https://registry.npmjs.org/node-dht-sensor
23 http 304 https://registry.npmjs.org/node-dht-sensor
24 silly get cb [ 304,
24 silly get   { date: 'Sun, 17 May 2015 10:19:50 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"B7YPB0FKNLKETDYQX2WQ50DG0"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ams4130-AMS',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1431857990.313875,VS0,VE372',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/node-dht-sensor from cache
26 verbose get saving node-dht-sensor to /home/pi/.npm/registry.npmjs.org/node-dht-sensor/.cache.json
27 silly addNameRange number 2 { name: 'node-dht-sensor', range: '*', hasData: true }
28 silly addNameRange versions [ 'node-dht-sensor',
28 silly addNameRange   [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7' ] ]
29 verbose addNamed node-dht-sensor@0.0.7
30 silly addNamed semver.valid 0.0.7
31 silly addNamed semver.validRange 0.0.7
32 silly cache afterAdd node-dht-sensor@0.0.7
33 verbose afterAdd /home/pi/.npm/node-dht-sensor/0.0.7/package/package.json not in flight; writing
34 verbose afterAdd /home/pi/.npm/node-dht-sensor/0.0.7/package/package.json written
35 silly install resolved [ { author: { name: 'David Momenso' },
35 silly install resolved     name: 'node-dht-sensor',
35 silly install resolved     description: 'Read data from DHT sensors on Raspberry Pi',
35 silly install resolved     version: '0.0.7',
35 silly install resolved     repository: { url: 'https://github.com/momenso/node-dht-sensor' },
35 silly install resolved     main: './build/Release/node-dht-sensor',
35 silly install resolved     dependencies: {},
35 silly install resolved     engines: { node: '>=0.12 <0.13' },
35 silly install resolved     license: 'LGPL',
35 silly install resolved     scripts: { install: 'node-gyp rebuild' },
35 silly install resolved     gypfile: true,
35 silly install resolved     gitHead: '01f52b7eb4acb024e6c0592dfcf6e0092c0dce42',
35 silly install resolved     bugs: { url: 'https://github.com/momenso/node-dht-sensor/issues' },
35 silly install resolved     homepage: 'https://github.com/momenso/node-dht-sensor',
35 silly install resolved     _id: 'node-dht-sensor@0.0.7',
35 silly install resolved     _shasum: '5646264968973e15fb650fa2444d151299834367',
35 silly install resolved     _from: 'node-dht-sensor@*',
35 silly install resolved     _npmVersion: '2.5.1',
35 silly install resolved     _nodeVersion: '0.12.0',
35 silly install resolved     _npmUser: { name: 'momenso', email: 'momenso@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '5646264968973e15fb650fa2444d151299834367',
35 silly install resolved        tarball: 'http://registry.npmjs.org/node-dht-sensor/-/node-dht-sensor-0.0.7.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/node-dht-sensor/-/node-dht-sensor-0.0.7.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install node-dht-sensor@0.0.7 into /home/pi
37 info installOne node-dht-sensor@0.0.7
38 verbose installOne of node-dht-sensor to /home/pi not in flight; installing
39 verbose lock using /home/pi/.npm/_locks/node-dht-sensor-2c3fc3d2e9bcb4e3.lock for /home/pi/node_modules/node-dht-sensor
40 silly install write writing node-dht-sensor 0.0.7 to /home/pi/node_modules/node-dht-sensor
41 silly cache addNamed cb node-dht-sensor@0.0.7
42 verbose unbuild node_modules/node-dht-sensor
43 verbose gentlyRm vacuuming /home/pi/node_modules/node-dht-sensor
44 verbose tar unpack /home/pi/.npm/node-dht-sensor/0.0.7/package.tgz
45 verbose tar unpacking to /home/pi/node_modules/node-dht-sensor
46 verbose gentlyRm vacuuming /home/pi/node_modules/node-dht-sensor
47 silly gunzTarPerm modes [ '755', '644' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm extractEntry .npmignore
50 silly gunzTarPerm extractEntry README.md
51 silly gunzTarPerm extractEntry LICENSE
52 silly gunzTarPerm extractEntry test-spec.js
53 silly gunzTarPerm extractEntry test.js
54 silly gunzTarPerm extractEntry binding.gyp
55 silly gunzTarPerm extractEntry node-dht-sensor.cpp
56 info preinstall node-dht-sensor@0.0.7
57 silly install resolved []
58 verbose about to build /home/pi/node_modules/node-dht-sensor
59 info build /home/pi/node_modules/node-dht-sensor
60 verbose linkStuff [ false, false, false, '/home/pi/node_modules' ]
61 info linkStuff node-dht-sensor@0.0.7
62 verbose linkBins node-dht-sensor@0.0.7
63 verbose linkMans node-dht-sensor@0.0.7
64 verbose rebuildBundles node-dht-sensor@0.0.7
65 info install node-dht-sensor@0.0.7
66 verbose unsafe-perm in lifecycle true
67 info node-dht-sensor@0.0.7 Failed to exec install script
68 verbose unlock done using /home/pi/.npm/_locks/node-dht-sensor-2c3fc3d2e9bcb4e3.lock for /home/pi/node_modules/node-dht-sensor
69 verbose stack Error: node-dht-sensor@0.0.7 install: `node-gyp rebuild`
69 verbose stack Exit status 1
69 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
69 verbose stack     at EventEmitter.emit (events.js:110:17)
69 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
69 verbose stack     at ChildProcess.emit (events.js:110:17)
69 verbose stack     at maybeClose (child_process.js:1008:16)
69 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
70 verbose pkgid node-dht-sensor@0.0.7
71 verbose cwd /home/pi
72 error Linux 3.18.11+
73 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "node-dht-sensor"
74 error node v0.12.1
75 error npm  v2.5.1
76 error code ELIFECYCLE
77 error node-dht-sensor@0.0.7 install: `node-gyp rebuild`
77 error Exit status 1
78 error Failed at the node-dht-sensor@0.0.7 install script 'node-gyp rebuild'.
78 error This is most likely a problem with the node-dht-sensor package,
78 error not with npm itself.
78 error Tell the author that this fails on your system:
78 error     node-gyp rebuild
78 error You can get their info via:
78 error     npm owner ls node-dht-sensor
78 error There is likely additional logging output above.
79 verbose exit [ 1, true ]
80 verbose unbuild node_modules/node-dht-sensor
81 info preuninstall node-dht-sensor@0.0.7
82 info uninstall node-dht-sensor@0.0.7
83 verbose unbuild rmStuff node-dht-sensor@0.0.7 from /home/pi/node_modules
84 info postuninstall node-dht-sensor@0.0.7
85 verbose gentlyRm vacuuming /home/pi/node_modules/node-dht-sensor
86 silly gentlyRm purging /home/pi/node_modules/node-dht-sensor
87 silly gentlyRm removing /home/pi/node_modules
88 silly gentlyRm finished vacuuming up to /home/pi

who can help me out?

**Comment by momenso** [comment]
To solve this, please follow instructions on http://www.airspayce.com/mikem/bcm2835/ to have the BCM2835 library installed. This library is a requirement for accessing the DHT sensor.
