### ISSUE TITLE
Raspberry Pi 2

### ISSUE THREAD

**Issue by craigmw** [momenso/node-dht-sensor#24]
Does this library work with the RPi2 now? The library seems to work fine on a Raspberry Pi B+, but not with the RPi 2 due to issues with the BCM library.

Thanks...

**Comment by momenso** [comment]
Yes, it works. You just have to install the appropriate BCM library. I have tested it with BCM2835 lib v1.39 a while back and it worked. But it should work with at least v1.44... Newer versions might not work tough...

**Comment by craigmw** [comment]
Okay, excellent. I haven't tried this yet, and will do so. Thanks for the help.
