### ISSUE TITLE
Raspberry Pi 1 Model B

### ISSUE THREAD

**Issue by jnovack** [momenso/node-dht-sensor#31]
I have a number of pis all over, and I found the following so I wanted it to be documented somewhere.  The following worked for me.

Raspberry Pi 1 Model B
Raspbian "Wheezy"
bcm2835-1.42
Node v0.10.17
node-dht-sensor@0.0.6

I found I had to downgrade bcm2835 (latest was 1.48, downgraded to 1.42), and node (latest was 4.3.7, downgraded to apt packaged v0.10.17), and consequently node-dht-sensor (0.0.6 works with node < v0.12).

Raspberry Pi 2 Model B
Raspbian "Jessie"
bcm2835-1.48
Node v4.3.7
node-dht-sensor@0.0.8

One caveat not mentioned in most install guides, is that I did a `modprobe w1-gpio` and `modprobe w1-therm` on both systems.

**Comment by rtclauss** [comment]
I've found that if you want to use this module with Node 4.x+ you need to update GCC on the RPi to at least 4.8.  I installed the module after following [this guide](https://somewideopenspace.wordpress.com/2014/02/28/gcc-4-8-on-raspberry-pi-wheezy/) prior to installing via npm.

**Comment by jnovack** [comment]
Raspbian Jessie works out of the box, you only need to `update`/`upgrade` on Wheezy.
