### ISSUE TITLE
Compatibility with latest node version

### ISSUE THREAD

**Issue by AuspeXeu** [momenso/node-dht-sensor#32]
I get the following warning when installing this package.

`npm WARN engine node-dht-sensor@0.0.8: wanted: {"node":">=0.12 <0.13"} (current: {"node":"4.2.1","npm":"2.14.7"})`

Would be great if this package runs on the latest node version

**Comment by momenso** [comment]
We have plans for an experimental version that will simplify general installation (i.e. BCM2835 library dependency) and be compatible with latest node.js
I'm hoping to have it available for testing soon.

**Comment by momenso** [comment]
Latest version already supports latest version of node.js.
Give it a try!

**Comment by AuspeXeu** [comment]
Cool, thanks! :+1:
