### ISSUE TITLE
issue : ACTION Regenerating Makefile

### ISSUE THREAD

**Issue by mehamindran** [momenso/node-dht-sensor#35]
make: Warning: File '../binding.gyp' has modification time 6157163 s in the future
  ACTION Regenerating Makefile
make: Warning: File '../binding.gyp' has modification time 6157163 s in the future
  ACTION Regenerating Makefile

This is happening When I do "npm install node-dht-sensor",
This is not stoping at any point,It's infinite loop.

**Comment by momenso** [comment]
This most likely related to your system having date/time badly configured.

**Comment by umar-muneer** [comment]
> This most likely related to your system having date/time badly configured.

A four-year-old comment saved at least an hour's effort. Thanks 👍

**Comment by rdwnsjjd** [comment]
> > This most likely related to your system having date/time badly configured.
> 
> A four-year-old comment saved at least an hour's effort. Thanks 👍

and for me after two years from this comment!
thanks again!
