### ISSUE TITLE
running as non-root seg-faults on new system with /dev/memgpio

### ISSUE THREAD

**Issue by BTBlueSkies** [momenso/node-dht-sensor#39]
I am getting seg-faults running this module as non-root. I know you mention it has to run as root, but I installed the latest BCM2835 which states that he is now using the /dev/memgpio.

Basically, just a heads up if you haven't tested this yet.

**Comment by stlhrt** [comment]
bcm2835_delayMicroseconds is causing the segfaults... seems like a bug in bcm2835 v1.50

**Comment by momenso** [comment]
Please try the latest release ```node-dht-sensor@0.0.13``` - this should fix this issue.
