### ISSUE TITLE
Script output 0 temp 0 hum

### ISSUE THREAD

**Issue by Yoda49** [momenso/node-dht-sensor#47]
Sensor AM2301 (DHT21). By datasheet  - timings identical to dht22 sensor, packet structure too.
Raspberry Pi with 26 pin header. OS raspbian.

With logic analyzer i get this signal. Its ok, but after CRC byte - there are three more bytes with zero.
![aaazzz](https://cloud.githubusercontent.com/assets/22234158/18580514/c33fc6d2-7c04-11e6-98a4-e1f1c067160e.png)

Init OK.
But script shows temperature 0 and pressure 0.

**Comment by momenso** [comment]
Nice! I haven't connected a logic analyzer yet to check this. I need to get one of these! (-:

In the current version the algorithm will discard this reading as invalid and you should be able to confirm it by the ```isValid``` attribute of the readout as follows.
```javascript
var readout = sensorLib.read();
readout.isValid // should be false in this case
```
Are you able to confirm if this 24 extra bits are always present? Even if you try to read again the sensor?

**Comment by Yoda49** [comment]
Yes, isValid = false, after reading sensor. Each time the sensor reading - at the end there are 24 null bits.

**Comment by momenso** [comment]
I couldn't find any sensors that behave like this but I added a patch to ```node-dht-sensor@0.0.24``` that should allow for it to read the sensor data even if these extra bits are present.
Give it a try and let me know what happens.

**Comment by Yoda49** [comment]
Now Avalid is TRUE, but script output temp: 1.00C and hum: 1.00% Its like on most significant byte of temp and hum. Problem in code.
![zz1](https://cloud.githubusercontent.com/assets/22234158/18588232/485c505a-7c2e-11e6-9231-6a4219b81575.png)
![aaazzz](https://cloud.githubusercontent.com/assets/22234158/18588577/bde1a84c-7c2f-11e6-9374-128b33a55b38.png)

**Comment by momenso** [comment]
It looks like you didn't configure the sensor type to decode from a **DHT22** sensor (i.e. type=22).
Make sure you initialize the sensor using the `sensorLib.initialize` and specify both the sensor type and the GPIO pin accordingly.
For example, you can see In the [first example](https://github.com/momenso/node-dht-sensor#first-example) the library is initialized to read a **DHT22** sensor from GPIO `4.` Otherwise, the library will default to DHT11 and it will produce the result you're getting.

**Comment by Yoda49** [comment]
I am sorry)  I forgot to change the sensor identifier from 11 to 22. Its work! Thanks!!!!

**Comment by momenso** [comment]
:thumbsup:
