### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nielsmouthaan** [momenso/node-dht-sensor#48]
While trying this package, I struggled with two things:

- The documentation states that the package works with "DHT11, DHT22 and AM2302 sensors". However, it is not completely clear that for the AM2302 sensor also 22  should be used;
- The pin number is not the physical pin but the BCM pin. While writing this it makes a bit more sense as the BCM2835 library is used. However, I was unable to get readings while I thought I was sure about the pin number provided. Clearly I was not.

Would be good if these things are described in a better way. Other than that, perfect!

**Comment by momenso** [comment]
Thanks @nielsmouthaan! Docs just updated based on your feedback.
