### ISSUE TITLE
HAP-NodeJS -> can't npm rebuild

### ISSUE THREAD

**Issue by Jakkawad** [momenso/node-dht-sensor#59]
![bcm](https://cloud.githubusercontent.com/assets/12533828/21808034/020dff76-d774-11e6-8106-00a8c04a3776.png)
after npm install node-dht-sensor, i can't npm rebuild how to fix it

thankyou

**Comment by momenso** [comment]
Looks the same as #56, can you confirm?

**Comment by momenso** [comment]
If you have any follow-up here please reopen this issue with details on how it's different from #56.
