### ISSUE TITLE
Can't pass humidity readings to Dashboard Gauge

### ISSUE THREAD

**Issue by knjigor** [momenso/node-dht-sensor#60]
Hi,
I have installed node-dht-sensor, I have RPI2 and DHT11 sensor, and I get readings correct, but I can't pass humidity to gauge (I can pass it to text component from node-dashboard as msg.humidity and msg.payload). My schema looks like this:

![node-red-dht11](https://cloud.githubusercontent.com/assets/1343947/22238089/ce6fc02c-e20f-11e6-8805-e57dacd3eded.png)

Problem is that in function msg.humidity returns temperature readings and msg.payload returns error (something "cant get readings", i'm not at home right now so I can't check).

I'm total beginner at this, so could someone please help me with this?

**Comment by momenso** [comment]
Is this a node-red project? Please confirm what are you using to get data from the sensor.
