### ISSUE TITLE
DHT11 : Problem with bcm2835_init

### ISSUE THREAD

**Issue by shakir1443** [momenso/node-dht-sensor#64]
I have successfully installed BCM2835 library in intel edison. After that I installed the package 'node-dht-sensor'. I have tried the sample program but it says : 
```
"bcm2835_init: mmap failed : Invalid Argument
Segmentation fault" 
```

**Comment by momenso** [comment]
Sorry but BCM2835 lib designed to work on Raspberry only.

**Comment by shakir1443** [comment]
Can you tell me what can I use to read data from DHT11 sensor by using intel edison along with NodeJs?

**Comment by momenso** [comment]
I am not aware of any complete implementations but you could extend the [node-dht-edison](https://github.com/picatextra/node-dht-edison) lib to support DHT11 (today it seems to support only DHT22)
