### ISSUE TITLE
Not working in RPi3

### ISSUE THREAD

**Issue by mmontes11** [momenso/node-dht-sensor#65]
start sensor read (type=11, pin=17).
*** timeout #2

I've checked wiring configuration with AdafruitDHT and it worked:

pi@raspberrypi:~/project/Adafruit_Python_DHT/examples $ ./AdafruitDHT.py 11 17
Temp=21.0*  Humidity=80.0%

I've checked this issue as well:
https://github.com/momenso/node-dht-sensor/issues/57

What's the problem? I'm going crazy

**Comment by run-towards** [comment]
What sensor are you using? What pin convention following? BCM or WPi? From latter it's possible that you are reading from incorrect pin

**Comment by momenso** [comment]
most likely incorrect pin configuration.

**Comment by mmontes11** [comment]
I'm sure I have correct pin configuration but sometimes I got a timeout, I think the problem is in sensors

BTW how can I configure a WPi approach ?

**Comment by saschakiefer** [comment]
I'm facing the exact same issue on the same hardware. The Python access is working for me as well. It's even working when I use the rpio library directly accessing the sensor with an own algorithm (since it's error prone I wanted to switch to the lib). 

#57 didn't fix my issue either.

**Comment by momenso** [comment]
Currently, there's no support for other GPIO library other than the standard BCM2835 library. If someone wants to give that a try feel free to contribute.

**Comment by battistaar** [comment]
Same for me, wiring configuration is correct (tested with AdafruitDHT).
[#57](https://github.com/momenso/node-dht-sensor/issues/57) didn't fix.

any news about it?

**Comment by mmontes11** [comment]
#57 didn't fix my issue either.

any news?

**Comment by fbrinker** [comment]
For me it is working on a RPI3 with BMC2835 and a DHT22
I am using this version: http://www.airspayce.com/mikem/bcm2835/bcm2835-1.52.tar.gz
Wired the DHT22 to Pin 11, GPIO 17 (so I pass 17 to the lib as second parameter)

**Comment by YannLeBihan** [comment]
Hi,

It's also working here on a RPI3 + DHT11 with BMC2835, wired to Pin 7 - GPIO 4.

One particularity of the sensor I'm using (a Velleman VMA311) is its pins order : signal on the left, + in the middle and - on the right. Will soon test it with a DHT22, too.

And btw, @momenso, thanks a lot for this very useful module.

**Comment by prasanpro** [comment]
It is working with RPi3 following instruction of installing node-gyp.

**Comment by momenso** [comment]
If you still have any problems please open a new issue with your specifics.
