### ISSUE TITLE
Getting only zeros

### ISSUE THREAD

**Issue by IbrahimaWane** [momenso/node-dht-sensor#67]
Temperature: 0.00C, Humidity: 0.00%

Above is the result I get whenever I run my file. I am using a dht11 sensor.
In order to check if the sensor is connected and working perfectly, I run a python file that uses Ardafruit library and it works fine. Do you have any suggestion please?
Thanks in advance.

**Comment by momenso** [comment]
Please see if #50 solves your problem.

**Comment by IbrahimaWane** [comment]
I tried and connected the data wire to the 5V wire using a 10kΩ resistor but still it didn't work.
I tried many pins. That one is GPIO 25 right?
![whatsapp image 2018-02-09 at 10 21 42 am](https://user-images.githubusercontent.com/35750957/36006994-9646ee5a-0d83-11e8-9cec-bea90ff66d9a.jpeg)

**Comment by momenso** [comment]
By the looks of it you're using a DHT11 module that should already have the required resistor in there.

Can you share the JavaScript code as well?

**Comment by IbrahimaWane** [comment]
Well, for the resistor, I tried it after you suggested #50 to me. But I tried without it. As for the javaScript code, I used your first example like this : "var sensor = require('node-dht-sensor');

sensor.read(11, 25, function(err, temperature, humidity) {
    if (!err) {
        console.log('temp: ' + temperature.toFixed(1) + '°C, ' +
            'humidity: ' + humidity.toFixed(1) + '%'
        );
    }
});" but it didn't show anything. I tried the second one even though I don't have a Dht22 module : "var sensorLib = require("node-dht-sensor");

var sensor = {
    sensors: [ {
        name: "Indoor",
        type: 11,
        pin: 25
    }, {
        name: "Outdoor",
        type: 22,
        pin: 4
    } ],
    read: function() {
        for (var a in this.sensors) {
            var b = sensorLib.read(this.sensors[a].type, this.sensors[a].pin);
            console.log(this.sensors[a].name + ": " +
              b.temperature.toFixed(1) + "°C, " +
              b.humidity.toFixed(1) + "%");
        }
        setTimeout(function() {
            sensor.read();
        }, 2000);
    }
};

sensor.read();", again this one shows only zeros.

**Comment by momenso** [comment]
Tried to replicate this issue with the following configuration on Raspbian running on a RPi 2 Model B and BCM2835 library **1.55**.

```javascript
var sensor = require('node-dht-sensor');

sensor.read(11, 25, function(err, temperature, humidity) {
  if (!err) {
    console.log('temp: ' + temperature.toFixed(0) + '  C, ' +
                'humidity: ' + humidity.toFixed(0) + '%');
  }
});
```
![image](https://user-images.githubusercontent.com/420851/36102427-72db63e8-0ff3-11e8-876a-c5cb46da45ea.png)

The DHT11 module however is not the same you're using.
![image](https://user-images.githubusercontent.com/420851/36102910-e78a74bc-0ff4-11e8-9b1e-ba1492f394ea.png)
Other than that it all works fine.

**Comment by MPursche** [comment]
Hello,

I ran into the same issue using a DHT11 and a Rasperry PI 3. I actually have two DHT11 for testing. One of them is kind of working(sometimes reading fails with a timeout) and the other isn't working at all.

I looked into the "dht-sensor.cpp"(Line 64) and I think I found the issue:
```c++
    // request sensor data
    bcm2835_gpio_fsel(pin, BCM2835_GPIO_FSEL_OUTP);
    bcm2835_gpio_write(pin, HIGH);
    usleep(10000);
    bcm2835_gpio_write(pin, LOW);
    usleep(type == 11 ? 2500 : 800); // <- pull down for only 2500 microseconds?
    bcm2835_gpio_write(pin, HIGH);
    bcm2835_gpio_fsel(pin, BCM2835_GPIO_FSEL_INPT);
```
According to the specs I found online for the DHT11 sensor the signal needs to be pulled down for at least 18 milliseconds, but in the code it is only pulled down for 2500 microseconds(or 2.5 milliseconds).
I increased the pulldown time to 18 milliseconds and now both sensors are working.

Greetings

Marcel

**Comment by momenso** [comment]
This might well be due to DHT11 from different manufacturers where some sensors might really require a longer pull down -- it didn't affect any the sensors I have for testing but hopefully it will help @IbrahimaWane and others.

Nice catch @MPursche ! Your contribution is already published in node-dht-sensor **v0.0.34**

@IbrahimaWane can you please try upgrading to 0.0.34 to see if this solves your issue?

**Comment by IbrahimaWane** [comment]
Hello
I upgraded and it works perfectly.
@momenso,  @MPursche, great job and thanks for the assistance.

**Comment by momenso** [comment]
Glad it worked. Thanks for the feedback @IbrahimaWane !
