### ISSUE TITLE
Hardware emulation

### ISSUE THREAD

**Issue by kothique** [momenso/node-dht-sensor#77]
I'm writing a web server that uses your library. The problem is development is being done on my PC which has no GPIO's, of course, so I can't test it if I install the library. Do you think it is possible to emulate sensors if GPIO's are not present?

https://github.com/jperkin/node-rpio, for example, has a `mock` option:

```js
var options = {
        gpiomem: true,          /* Use /dev/gpiomem */
        mapping: 'physical',    /* Use the P1-P40 numbering scheme */
        mock: undefined,        /* Emulate specific hardware in mock mode */
}
```

I'm not really familiar with the 'node <-> C/C++'  stuff, so my workaround doesn't seem too clear and legit: https://github.com/daisy-electronics/dht-sensor/commit/f68c1f6acb6f89411da18039265d30d099fb9bdd

Maybe you could turn me in the right direction to implement this properly, so I could create a pull request in the future?

**Comment by momenso** [comment]
It does seems like a legit need to mock out the sensor part of the app. I like the idea.

Perhaps we could try and move away from using the *BCM2835 library*. Using instead [node-rpio](https://github.com/jperkin/node-rpio) does look like a good candidate, what you think?

**Comment by kothique** [comment]
> It does seems like a legit need to mock out the sensor part of the app. I like the idea.
> 
> Perhaps we could try and move away from using the _BCM2835 library_. Using instead [node-rpio](https://github.com/jperkin/node-rpio) does look like a good candidate, what you think?

Sounds like a good idea in general.

`node-rpio` actually has an example that should work with `DHT11`: https://github.com/jperkin/node-rpio/blob/master/examples/dht11.js Though it didn't work for me. None of the solutions here did either: https://github.com/jperkin/node-rpio/issues/57 Can you try it out?

**Comment by kothique** [comment]
(not related to sensor reading itself)

Also, if we move to using `node-rpio`, it's gonna break compatibility as different pin numbering may be used depending on how `node-rpio` was inintialized. So in the new version we could probably rename synchronous `read` to `readSync`, and make `read` return a Promise if no callback is passed.

**Comment by momenso** [comment]
I did a quick test and example from rpio for reading a DHT11 sensor didn't work for me either. That's weird. I'll try to debug it to see if I can find something.

As for the port numbering we may be able to initialize rpio to use tge GPIO mapping. I saw this example from the docs:
```javascript
rpio.init({mapping: 'gpio'});   /* Use the GPIOxx numbering */
```
So, this really works there should be no problem with breaking compatibility.

**Comment by kothique** [comment]
I mean people would want to use `node-dht-sensor` along with `node-rpio`, so we cannot initialize `node-rpio` ourselves. Thus we cannot be sure what numbering is used.

**Comment by kothique** [comment]
Reading DHT sensor data requires precise timing, so I'm worried that node's function call overhead may cause it to be less reliable. Am I wrong?

**Comment by momenso** [comment]
You're right. It might be a problem but I wanted to test it first to see if it is really a problem.

**Comment by momenso** [comment]
I've got some valid readouts with a modified `dht.js` from *rpio* examples! Definitely not nearly as reliable as using *node-dht-sensor* but it did work after tweaking the timing and bit level threshold.

I've changed the following:
  1. MCU initialization timings to **5 ms** and **9 ms**, for HIGH and LOW respectively;
  2. Bit length cutoff to **> 350**;
  3. Bit level 1 when length **> 150** and 0 otherwise.

Any luck on your side?

**Comment by kothique** [comment]
No luck unfortunately. All I found out is if MCU intialization LOW timing is less than 11ms, then DHT response signal is always HIGH.

**Comment by kothique** [comment]
Anyway, even if I make it work for myself, calibrating these values for every different device, load, and lunar phase is not an option, is it?

**Comment by momenso** [comment]
Yes, it will be tricky to make it work reliably - I think we should park the rpio idea for now.

Lets go back to providing a mocking mode where we can provide fake readout values. Perhaps that is going to be useful, not a hardware emulation tough. The goal would be to enable it possible to develop an app when not having an actual **DHT** sensor connected to the **GPIO**, right?

**Comment by kothique** [comment]
More like not having GPIO's whatsoever.
