### ISSUE TITLE
Consistent indentation

### ISSUE THREAD

**Issue by kothique** [momenso/node-dht-sensor#89]
Identation is a mess now. Sometimes tabs, sometimes double spaces are used. It would also be nice to add `.editorconfig`.

**Comment by kothique** [comment]
I can do it. Just tell me what kind of indentation you prefer.

**Comment by momenso** [comment]
I'd go with +2 spaces for indentation. Or are you prefer tabs?

**Comment by kothique** [comment]
I use two spaces, too.
